### ISSUE TITLE
Saved game query can take a long time

### ISSUE THREAD

**Issue by Licktopia** [Licktopia/ChampionsOfSudoku2#10]

**Comment by Licktopia** [comment]
There may not be much of a solution for this as the byte array size is the likely culprit. If there is a way to reduce their size, it could help speed things up.

**Comment by jfkonecn** [comment]
I could try and simplify the byte array to store the minimum amount of data required to recreate the game state. 

Pros
If we change the game class in the future all old saved games wouldn't necessarily be corrupted.
Stores less data

Cons
It would be must easier to forget to include important pieces of data.

I think it might be worth doing when if we feel that the game class is more or less, from the critical variables  standpoint, is not going to change much.

**Comment by Licktopia** [comment]
Sounds good, it's not a huge issue now... so I put it in the won't fix category so we can figure it out later.

**Comment by Licktopia** [comment]
Actually I think I can fix this. The initial query to populate the list will not include the byte arrays. Then when resume game is clicked, it will just download the one byte array that is needed.

**Comment by Licktopia** [comment]
Took the byte array out of the SavedGame Object so that the list populates with just metadata instead of storing a complete list of all saved games and their byte arrays. Then when I specific game is clicked on to resume, only that byte array is downloaded. Seems to work much much faster and I would assume eat less memory since all the byte arrays aren't hanging around in local memory.
