### ISSUE TITLE
Add additional statistics to support the multiplayer UI.

### ISSUE THREAD

**Issue by jfkonecn** [Licktopia/ChampionsOfSudoku2#12]
Make comments about any features the UI needs from the MultiGame classes.

**Comment by Licktopia** [comment]
One thing I think we should add here is some kind of multiplayer leaderboard.  Perhaps you could get points x the number of opponents (but not using the multiplier).  Those points could go into your multiplayer total points. Also those points could count towards your total xp as well so you can still rank up and stuff playing multiplayer. Or maybe not, as people could cheat and play themselves.

**Comment by jfkonecn** [comment]
I think it would be a nice feature. Like you said there is a good chance someone could cheat. However, we could something like a "ranked game" where you're forced to do an auto picked match.

Another thing to note is that all the messages being sent in the multiplayer are unencrypted. So I suppose if someone really wanted to cheat they could send fake messages about their game state. I don't think it's that big of deal since the data we're sending isn't sensitive, but it's someone to keep in mind.

https://developers.google.com/games/services/common/concepts/realtimeMultiplayer
![image](https://user-images.githubusercontent.com/24961694/29692942-b05bdba0-8900-11e7-96ea-cf396f3e2dc2.png)

**Comment by Licktopia** [comment]
It's probably not hard to encrypt the messages.... But we can worry about that when we have to. Let me know if you want me to help you with the Leaderboard. It's pretty straightforward to set up.

**Comment by jfkonecn** [comment]
Here are some common techniques
https://www.storagecraft.com/blog/5-common-encryption-algorithms/

RSA is one we went over in networks

Here's how it works
[Lecture42.pdf](https://github.com/Licktopia/ChampionsOfSudoku2/files/1252718/Lecture42.pdf)

Here's how to do it in Java
https://javadigest.wordpress.com/2012/08/26/rsa-encryption-example/

It would require much more data since every single peer would require their own public key. This effectively would mean that we would have to send a different message to each person in the room. I'm not sure encrypting the messages is worth upping the user's data usage.

I'll add valid data checks to prevent the app from crashing, but somethings else we could do is to flag suspicious games/have a report system and just ban people who cheat from using the app. I feel like that would be something we could work on in the future if we have lots of people using the app.

**Comment by Licktopia** [comment]
I would say not high on the priority list now, but it's interesting for sure. I mean it's just one of those things where if one of us wakes up one day and decides hey it'd be a fun challenge to do encryption then cool. But we're not sending financial info or government secrets so we don't need anything super secure either. For the leaderboards it allows you to send an extra parameter with the score, and for the old version I randomly generated a number.... like 5*score^firstdightofday + 13 -minutes*11 or something weird just to add some kind of validation to the leaderboard submission.  Like if we suspected someone of cheating we could inspect that number and it'd have to be correct. One could still try and figure that out but it'd be alot of work to do that to cheat on a sudoku app.

**Comment by jfkonecn** [comment]
Okay that probably would be a good thing to add for the leaderboard submission.

In the mean time I think I'll work on making a function to evaluate players for the leaderboard.

I was planning on making the function based the following:
User's Game Score
Bonus points for winning (based on the opponent's XP)

Do you think those are good variables to base it on?

**Comment by Licktopia** [comment]
Yeah I think however you dream it up... One consideration is if we want it to be cumulative or just on a game by game basis, like the best game score vs most total xp. Could do both or just one or the other. To do cumulative I'd probably query to get the users total when the game starts. Then query again when it ends just to be sure... add the new amount and submit it

**Comment by Licktopia** [comment]
I think right now I put in #1337" for the second parameter of the leaderboard submissions so if you want you can change that to some sort of verification code
