### ISSUE TITLE
Signin button is invisible after competing a game

### ISSUE THREAD

**Issue by jfkonecn** [Licktopia/ChampionsOfSudoku2#16]
When you complete a game and you go back to the main menu, the signin button becomes invisible.

Step to Recreate Bug:
From the completed game screen. Click continue
![image](https://user-images.githubusercontent.com/24961694/29690456-10168b1e-88f5-11e7-8790-8fb82a530dde.png)

You will go to the main menu and see that the sign in button is invisible
![capture](https://user-images.githubusercontent.com/24961694/29690354-a2f4224e-88f4-11e7-86ad-f468b2963743.JPG)

**Comment by Licktopia** [comment]
So I tried to recreate this by hitting solve now and then going to the main menu. I did those both signed in and not signed in but could not reacreate the problem. I am wondering if you leveled up maybe? ALthough it doesn't show the level up in the first screenshot.

**Comment by jfkonecn** [comment]
It only happens when you beat the board without clicking the solve now button

**Comment by Licktopia** [comment]
Does it the badge come in after a few seconds or not at all?

**Comment by jfkonecn** [comment]
Not at all

**Comment by Licktopia** [comment]
I think this is pretty much taken care of. I had to write out a logic tree to figure out what was going on. I think it is livable now.
