### ISSUE TITLE
Incorrectly marked Hidden Pair

### ISSUE THREAD

**Issue by Licktopia** [Licktopia/ChampionsOfSudoku2#24]
![screenshot_20170902-025147](https://user-images.githubusercontent.com/23268081/29993632-c4cc06ec-8f8a-11e7-85a4-75478e332eb8.png)
![screenshot_20170902-025554](https://user-images.githubusercontent.com/23268081/29993633-c65e8a70-8f8a-11e7-8262-4b786c21d148.png)

**Comment by MKormann** [comment]
Were you able to recreate this at all or was it just in this one instance?  Trying to take a look at it now

**Comment by Licktopia** [comment]
yeah it was failry easy to recreate on other boards. 
![screenshot_20170902-041846](https://user-images.githubusercontent.com/23268081/29999761-951796b2-9022-11e7-8bd2-680a145e8768.png)

**Comment by Licktopia** [comment]
Also let me know what you think about the hints ui... especially the color mode. The y-wing for example I'm not sure it's meaningful what's being shown. Let me know whatever changes you think should be made.

**Comment by MKormann** [comment]
Got it.  Bug was for hidden pairs that were consecutive numbers.  Fixed.
