### ISSUE TITLE
Crash when quitting game to main menu

### ISSUE THREAD

**Issue by MKormann** [Licktopia/ChampionsOfSudoku2#26]
![image](https://user-images.githubusercontent.com/7059691/29999972-2547ed4e-9029-11e7-8f66-bcd3fef39529.png)

Clicking top left icon to get to main menu during a game crashes.

**Comment by Licktopia** [comment]
SO i fixed this and made a push. It's crashing while db is being queried, and swapping fragments is killing fragments on the backstack. Now that the memory issue is fixed, we can probably go back to leaving fragments on the backstack
