### ISSUE TITLE
Naked Triple weirdness

### ISSUE THREAD

**Issue by Licktopia** [Licktopia/ChampionsOfSudoku2#27]
All from the same game. Puzzle number is included in the screenshot.
![screenshot_20170903-231117](https://user-images.githubusercontent.com/23268081/30043317-af0bd54e-91c4-11e7-8576-65a3b0d05aea.png)
![screenshot_20170903-231034](https://user-images.githubusercontent.com/23268081/30043320-b0a3210a-91c4-11e7-8ea3-be67921f1376.png)
![screenshot_20170903-231416](https://user-images.githubusercontent.com/23268081/30043323-b1be95c4-91c4-11e7-885b-b8a8ad90fdaa.png)
![screenshot_20170903-231104](https://user-images.githubusercontent.com/23268081/30043324-b366281a-91c4-11e7-9643-8e8423995eb3.png)
![screenshot_20170903-231045](https://user-images.githubusercontent.com/23268081/30043326-b4b842f2-91c4-11e7-9e7e-82d6bac86f37.png)
![screenshot_20170903-231108](https://user-images.githubusercontent.com/23268081/30043327-b62e2f98-91c4-11e7-8172-7cff9efa8cb9.png)

**Comment by MKormann** [comment]
Fixed.  A few lines were still checking squares that had user notepad values then were filled in.
