### ISSUE TITLE
Pressing hint buttons fills small notepads but should go away when released

### ISSUE THREAD

**Issue by Licktopia** [Licktopia/ChampionsOfSudoku2#8]

**Comment by MKormann** [comment]
I mentioned this in the other thread, but this is probably a better spot to discuss what we want to do with the hints.  Should they only be operating on the notepad the user has filled out as we discussed before?  Or should it fill in a complete notepad and display the hints, then go back to the users board?

**Comment by Licktopia** [comment]
It's sort of a tricky one but I might be tempted to say that while pressed it should show all squares with the correct notepad filled out, and then on release reverts back to the way the user had it.  But I'm not too strongly opinionated. If we do it this way I think that there should be a good size penalty for using hints, including the timer idea, dropping your score every 200 ms or something.
